# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87b50aada2befd86d2afabe61e32cd02973d6d72066354ed81534208b1ed71e342945988d0ef9b154066647402e529ca86856530c2d961f78141c97ea4f0a4a

test:
  secret_key_base: 15d44804e2bde0e0673692f7ff68345b48ef88c936d31385d5208ac31fce706f2e083cd8c6e646fd0a3924693dd9e7e525a205157e242dea003ace0baa208c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
